# Generated by Django 2.0.2 on 2019-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='inativo',
            field=models.NullBooleanField(default=False),
        ),
    ]
