# Generated by Django 2.0.2 on 2019-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=120)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
