# Generated by Django 2.0.2 on 2019-04-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.CharField(blank=True, max_length=120, null=True)),
                ('fuma', models.BooleanField()),
                ('fuma_frequencia', models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True)),
                ('bebe', models.BooleanField()),
                ('bebe_frequencia', models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True)),
                ('pratica_atividade', models.BooleanField()),
                ('pratica_frequencia', models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
            options={
                'db_table': 'quadro_clinico',
            },
        ),
    ]
